// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: news.sql

package sqlc

import (
	"context"
)

const getLatestNews = `-- name: GetLatestNews :one
SELECT id, title, content, created_at, updated_at, deleted_at FROM news
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestNews(ctx context.Context) (News, error) {
	row := q.db.QueryRow(ctx, getLatestNews)
	var i News
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
