
on: 
  push:
    branches: 
      - main

name: Terraform Apply

permissions:
  contents: read
  pull-requests: write
  id-token: write 

jobs:
  plan:
    runs-on: ubuntu-latest
    name: Apply terraform plan
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}            
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure ACR credentials
        if: ${{ github.event_name == 'push' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE_ARN }}

      - name: Write variables and backend files
        run: |
          cat << 'EOF' > prod.s3.tfbackend
          ${{ secrets.TF_BACKEND }}
          EOF
          cat << 'EOF' > prod.tfvars
          ${{ secrets.TF_VARiABLEs }}
          EOF

      - name: Terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: deploy
          var_file: prod.tfvars
          backend_config_file: prod.s3.tfbackend